version: '2'

services:
  web:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    ports:
      - "5000:8080"

  client:
    build:
      context: ./python
      dockerfile: Dockerfile
